import {test,expect} from '@playwright/test'
import {fixture} from './profile-fixture'
const destination=process.env.PROFILE_SCREENSHOT_DIR || 'work/profile-screenshots'
for(const width of [390,768,1440])for(const lang of ['bg','en'] as const)for(const dark of [false,true])test(`profile workspace ${width} ${lang} ${dark?'dark':'light'}`,async({page})=>{
 await page.setViewportSize({width,height:900})
 await fixture(page,lang,'pro')
 let name='Profile test',enabled:string[]=[],consent=false,prefs:any={enabled:false,cities:[],categories:[]}
 const mutations:string[]=[]
 await page.route('**/api/profile',r=>{if(r.request().method()==='PATCH'){name=r.request().postDataJSON().name;mutations.push('name')}return r.fulfill({json:{name,email:'profile@example.invalid',plan:'pro',permissions:[]}})})
 await page.route('**/api/alerts**',r=>{if(r.request().method()==='PATCH'){enabled=r.request().postDataJSON().enabled;mutations.push('weather')}return r.fulfill({json:{contractVersion:2,pro:true,enabled,alerts:[]}})})
 await page.route('**/api/activity',r=>{if(r.request().method()==='PATCH'){consent=r.request().postDataJSON().enabled;mutations.push('consent')}return r.fulfill({json:{enabled:consent,revision:null}})})
 await page.route('**/api/push',r=>{if(r.request().method()==='PATCH'){prefs=r.request().postDataJSON();mutations.push('push')}return r.fulfill({json:{contractVersion:1,pro:true,preferences:prefs,devices:[],registrationEnabled:false,publicKey:null,deliveryEnabled:false}})})
 if(dark)await page.getByRole('button',{name:'🌙',exact:true}).click()
 const opener=page.locator('.auth-nav').getByRole('button',{name:lang==='bg'?'Моят профил':'My profile',exact:true})
 await opener.click()
 const dialog=page.getByRole('dialog'), tabs=dialog.getByRole('tab')
 await expect(dialog.locator('.profile-plan')).toContainText(lang==='bg'?'Pro план':'Pro plan')
 await expect(dialog.getByRole('tabpanel')).toHaveCount(1)
 const input=dialog.getByLabel(lang==='bg'?'Име (незадължително)':'Name (optional)')
 await input.fill('New name')
 await tabs.nth(0).focus();await page.keyboard.press('ArrowDown');await expect(tabs.nth(1)).toBeFocused()
 const weather=dialog.locator('.notification-settings')
 await expect(weather.locator('input')).toHaveCount(8)
 await weather.locator('input').nth(0).check()
 await tabs.nth(2).click()
 const push=dialog.locator('.push-settings')
 await push.getByRole('button',{name:lang==='bg'?'Добави София':'Add София',exact:true}).click()
 await push.getByLabel(lang==='bg'?'Силен вятър':'Strong wind',{exact:true}).check()
 await expect(push.getByRole('button',{name:lang==='bg'?'Разреши и регистрирай това устройство':'Allow and register this device'})).toBeDisabled()
 await tabs.nth(0).click();await expect(input).toHaveValue('New name')
 page.once('dialog',d=>d.dismiss());await page.keyboard.press('Escape');await expect(dialog).toBeVisible()
 await dialog.getByRole('button',{name:lang==='bg'?'Запази':'Save',exact:true}).click()
 await expect(dialog.locator('.auth-success')).toBeVisible()
 for(let i=0;i<4;i++){
  await tabs.nth(i).click();await expect(dialog.getByRole('tabpanel')).toHaveCount(1)
  expect(await dialog.evaluate(e=>e.scrollWidth<=e.clientWidth+1)).toBe(true)
  expect(await dialog.locator('.auth-dialog-content').evaluate(e=>e.scrollWidth<=e.clientWidth+1)).toBe(true)
  await dialog.screenshot({path:`${destination}/profile-${width}-${lang}-${dark?'dark':'light'}-${i}.png`})
 }
 await tabs.nth(1).click();await expect(weather.locator('input').nth(0)).toBeChecked()
 await weather.getByRole('button',{name:lang==='bg'?'Запази метео настройките':'Save weather preferences'}).click()
 await expect(weather.getByRole('status')).toBeVisible()
 await tabs.nth(2).click();await expect(push.getByLabel(lang==='bg'?'Силен вятър':'Strong wind',{exact:true})).toBeChecked()
 await push.getByRole('button',{name:lang==='bg'?'Запази push настройките':'Save push preferences'}).click()
 await expect(push.getByRole('status')).toContainText(lang==='bg'?'запазени':'saved')
 await tabs.nth(3).click();await dialog.locator('.activity-consent input').check();await expect(dialog.locator('.activity-consent input')).toBeEnabled()
 expect(mutations).toEqual(['name','weather','push','consent'])
 // The parent blocks closing until all section saves have settled.
 await expect(dialog.getByRole('button',{name:lang==='bg'?'Затвори':'Close',exact:true})).toBeEnabled()
 await page.keyboard.press('Escape');await expect(dialog).toHaveCount(0);await expect(opener).toBeFocused()
})

test('focus trap, backdrop cancellation, failed weather save retains draft, compact auth',async({page})=>{
 await fixture(page,'bg')
 await page.locator('.auth-nav').getByRole('button',{name:'Моят профил',exact:true}).click()
 await page.getByRole('tab',{name:'Метео известия'}).click()
 const panel=page.locator('.notification-settings')
 await expect(panel.locator('input').nth(5)).toBeDisabled()
 await panel.locator('input').first().check()
 await page.route('**/api/alerts**',r=>r.fulfill({status:503,json:{}}))
 await panel.getByRole('button',{name:'Запази метео настройките'}).click()
 await expect(panel.getByRole('alert')).toBeVisible();await expect(panel.locator('input').first()).toBeChecked()
 const last=panel.getByRole('button',{name:'Изключи всички'});await last.focus();await page.keyboard.press('Tab');await expect(page.getByRole('button',{name:'Затвори',exact:true})).toBeFocused()
 await page.keyboard.press('Shift+Tab');await expect(last).toBeFocused()
 page.once('dialog',d=>d.dismiss());await page.locator('.auth-backdrop').click({position:{x:2,y:2}});await expect(page.getByRole('dialog')).toBeVisible()
 page.once('dialog',d=>d.accept());await page.keyboard.press('Escape');await expect(page.getByRole('dialog')).toHaveCount(0)
 await page.locator('.auth-nav').getByRole('button',{name:'Изход',exact:true}).click()
 for(const action of ['Вход','Регистрация']){
  await page.locator('.auth-nav').getByRole('button',{name:action,exact:true}).click()
  expect((await page.getByRole('dialog').boundingBox())!.width).toBeLessThanOrEqual(440)
  await page.keyboard.press('Escape');await expect(page.getByRole('dialog')).toHaveCount(0)
 }
 await page.locator('.auth-nav').getByRole('button',{name:'Вход',exact:true}).click();await page.getByRole('button',{name:'Забравена парола?',exact:true}).click()
 expect((await page.getByRole('dialog').boundingBox())!.width).toBeLessThanOrEqual(440)
 await page.keyboard.press('Escape')
})

for(const lang of ['bg','en'] as const)test(`coordinate city draft lifecycle ${lang}`,async({page})=>{
 await fixture(page,lang)
 let preferences:any={enabled:false,cities:[],categories:[]},fail=false
 await page.route('**/api/push',r=>{
  if(r.request().method()==='PATCH'){
   if(fail)return r.fulfill({status:503,json:{error:'ISOLATED_FAILURE'}})
   preferences=r.request().postDataJSON()
  }
  return r.fulfill({json:{contractVersion:1,pro:false,preferences,devices:[],registrationEnabled:false,publicKey:null,deliveryEnabled:false}})
 })
 await page.locator('.auth-nav').getByRole('button',{name:lang==='bg'?'Моят профил':'My profile',exact:true}).click()
 await page.getByRole('tab',{name:lang==='bg'?'Push известия':'Push notifications',exact:true}).click()
 const panel=page.locator('.push-settings'),details=panel.locator('details')
 await details.locator('summary').click()
 const city=details.getByLabel(lang==='bg'?'Име на град':'City name')
 await city.fill('Test town')
 await details.getByLabel(lang==='bg'?'Географска ширина':'Latitude').fill('42.5')
 await details.getByLabel(lang==='bg'?'Географска дължина':'Longitude').fill('24.5')
 await details.getByRole('button',{name:lang==='bg'?'Добави град':'Add city',exact:true}).click()
 await expect(city).toHaveValue('')
 await expect(panel.locator('li')).toContainText('Test town')
 await expect(page.locator('.profile-draft-note')).toBeVisible()
 fail=true
 const save=panel.getByRole('button',{name:lang==='bg'?'Запази push настройките':'Save push preferences'})
 await save.click();await expect(panel.getByRole('status')).toContainText(lang==='bg'?'не е потвърдена':'not confirmed')
 await expect(page.locator('.profile-draft-note')).toBeVisible()
 fail=false;await save.click();await expect(panel.getByRole('status')).toContainText(lang==='bg'?'запазени':'saved')
 await expect(page.locator('.profile-draft-note')).toHaveCount(0)
 // An unsuccessful duplicate add must keep the user's unfinished input.
 await city.fill('Duplicate')
 await details.getByLabel(lang==='bg'?'Географска ширина':'Latitude').fill('42.5')
 await details.getByLabel(lang==='bg'?'Географска дължина':'Longitude').fill('24.5')
 await details.getByRole('button',{name:lang==='bg'?'Добави град':'Add city',exact:true}).click()
 await expect(city).toHaveValue('Duplicate');await expect(panel.locator('li')).toHaveCount(1)
 page.once('dialog',d=>d.dismiss());await page.keyboard.press('Escape');await expect(page.getByRole('dialog')).toBeVisible()
 await city.fill('');await expect(page.locator('.profile-draft-note')).toHaveCount(0)
 await expect(page.getByRole('button',{name:lang==='bg'?'Затвори':'Close',exact:true})).toBeEnabled()
 let prompted=false;page.once('dialog',async d=>{prompted=true;await d.dismiss()})
 await page.keyboard.press('Escape');await expect(page.getByRole('dialog')).toHaveCount(0);expect(prompted).toBe(false)
 expect(preferences.cities).toEqual([{name:'Test town',latitude:42.5,longitude:24.5,zone:'Europe/Sofia'}])
})
